name: pruebas hola mundo docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1 - Checkout Repositorio
        uses: actions/checkout@v4

      - name: Paso 2 Login docker GitHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Paso 3 - configurar la imagen docker
        run: docker build -t contenedor .
      - name: Paso extra - Verificar imágenes Docker
        run: docker images
      - name: Paso 4 - Ejecutar extractor
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/static/csv":/Activida1Scraping/static/csv \
            -v "${{ github.workspace }}/static/db":/Activida1Scraping/static/db \
            contenedor edu_pad.main_extractora

      - name: Paso 5 - Ejecutar ingesta
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/static/csv":/Activida1Scraping/static/csv \
            -v "${{ github.workspace }}/static/db":/Activida1Scraping/static/db \
            contenedor edu_pad.main_ingesta

      - name: Paso 6 - Ejecutar Monitor
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/static/csv":/Activida1Scraping/static/csv \
            -v "${{ github.workspace }}/static/db":/Activida1Scraping/static/db \
            -v "${{ github.workspace }}/static/logs":/Activida1Scraping/static/logs \
            -e EMAIL_SENDER=${{ secrets.EMAIL_SENDER }} \
            -e EMAIL_RECEIVER=${{ secrets.EMAIL_RECEIVER }} \
            -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
            -e SMTP_SERVER=${{ secrets.SMTP_SERVER }} \
            -e SMTP_PORT=${{ secrets.SMTP_PORT }} \
            contenedor edu_pad.monitor